# Generated by Django 3.0.4 on 2020-03-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='eng_name',
            field=models.CharField(max_length=100, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='russian_name',
            field=models.CharField(max_length=100, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
    ]
