# Generated by Django 3.0.4 on 2020-03-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200313_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Петя Иванов', max_length=50, verbose_name='Полное имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
