# Generated by Django 3.0.4 on 2020-03-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200315_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='name',
        ),
    ]
